# HSMS JMeter defaults
users=100
rampUp=20
loops=1
thinkTimeMs=250
maxResponseMs=2000

protocol=http
host=localhost
port=5162

username=admin
password=Admin@123
productId=1
supplierId=1
saleId=1
userId=1
